### ISSUE TITLE
脚本能否增加一个总菜单？

### ISSUE THREAD

**Issue by DeeEi** [crazypeace/xray-vless-reality#1]
1、安装 Xray Vless Reality 节点
2、卸载 Xray
3、关闭、开启、重启 Xray
4、修改 Xray Vless Reality 节点配置
5、显示 Xray Vless Reality 节点链接
6、更新 Xray 内核
7、退出

**Comment by crazypeace** [comment]
欢迎你fork我的项目, 实现你说的这些功能.

安装 就是脚本执行一遍

卸载就是这里一行命令
https://github.com/crazypeace/xray-vless-reality#uninstall

关闭、开启、重启 Xray, 就是
systemctl 命令

修改 Xray Vless Reality 节点配置, 就是
卸载, 再用新参数安装一遍

显示 Xray Vless Reality 节点链接, 就是显示这个文件内容
~/_vless_reality_url_

更新 Xray 内核, 就是安装 xray 内核的命令再执行一遍
https://github.com/crazypeace/xray-vless-reality/tree/main#安装xray

**Comment by DeeEi** [comment]
![2024-11-25_102903](https://github.com/user-attachments/assets/63fba58a-6556-42fe-b34b-d6ed9c81b77a)

想运行脚本 bash <(curl -L https://github.com/crazypeace/xray-vless-reality/raw/main/install.sh) 后先是类似上面这个总菜单界面，有个总菜单方便小白后期查看和维护。

我还是希望这里上游实现。很抱歉我不太会改代码。

**Comment by crazypeace** [comment]
问问 gpt

https://poe.com/s/IX5X34t8bpX1UNLskaJB

**Comment by crazypeace** [comment]
谢谢你的真诚.

不过, 我只有兴趣实现底层基本逻辑. 不准备做一个大而全的保姆式的菜单脚本.

我希望我的脚本足够简单, 方便阅读 理解, 这样大家可以在此基础上做出满足自己需求的脚本.
